# Generated by Django 4.2.19 on 2025-02-08 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contacts_api", "0001_initial"),
    ]

    operations = []
